### PR TITLE
 Modifies Controller/Index View to pass on business information

### PR DESCRIPTION
**Pull request by nateptay**
Business information is stored in the ApplicationViewModel, then the Business owner's First and Last name are retrieved in a confirmation page.

### CODE REVIEW

**Review by edmundchan8 — APPROVED** [review]
Able to enter data and get to the information screen with displays my name, working great!

**Review by SkutchWill — COMMENTED** [review]
It does take the information and pass the user to a confirmation page with first name and last name.  I'm wondering why all the information entered on the phone is being carried in the URL though.

**Review by MatinMirzaei — APPROVED** [review]

**Comment by nateptay** [comment]
Will, I think the reason it's in the url is because I'm passing the object directly to the view. Once the database is set up we can store the object to the database, and then pass the user's ID to the view to retrieve the data

**Review by SkutchWill — APPROVED** [review]
Sounds good to me

**Review by madelynmlocke — APPROVED** [review]

**Pull request merged**
