### PR TITLE
Bugfix delete images and other appearance related updates

### LINKED ISSUE #107: Fix images not being deleted when a business is deleted
**DOD**: When a business is deleted, the images in the uploads folder are also deleted with it.

**Description**: Currently, images associated with a business do not have their images deleted from the database, even though a business will get deleted.

**User Story**: An administrator chooses a business to delete.  When that business is removed from the database, the images associated with that business should also be removed.

### PR DESCRIPTION
**Pull request by edmundchan8**
Closes #107

### CODE REVIEW

**Review by nateptay — CHANGES_REQUESTED** [review]
image
I tried testing it on a business that used both images and got the exception "The process cannot access the file [filename] because it is being used by another process". It came from line 559 in the AdminController.cs file. Hopefully the screenshot is visible, but I'll also put it on slack.

**Review by nateptay — DISMISSED** [review]
Looks like it's because it was being tracked by visual studio in the commit spot. As soon as I committed I was able to delete the business and the images disappeared just fine so I think you're good...

**Comment by edmundchan8** [comment]
@nateptay Interesting find, I'll see if I can find a way to recreate that on my end

**Comment by edmundchan8** [comment]
@nateptay I think I know why it happens, will try to find a way to fix it

**Comment by edmundchan8** [comment]
@nateptay @madelynmleahu I removed some of the code from the confirmDelete view, I added something to it in this pull request to show the images on the view just before you delete it.  Looks like the image is still being used as the deletion code is being processed.  Best to take it out for the time being.

**Review by nateptay — APPROVED** [review]
@edmundchan8 The same error popped up with the updated version and went away with the same trick as last time. I'm pretty sure it's just visual studio stopping it from working. The image is probably saved as a file that's going to be committed, so VS has it locked up. To get the error I add a new business, give it both images (and fill in the required fields), then hit submit. After the confirm page I go immediately to the search page, hit search, and try to delete the business. When I click the Confirm Delete button it throws the Internal Server Error. All this to say you can leave the logo out or put it back, and I don't think it'll be an issue once we get it up onto azure.

**Comment by edmundchan8** [comment]
@nateptay Weird, let's leave the logo out for the time being, but thanks for the feedback!

**Review by nateptay — APPROVED** [review]

**Review by madelynmlocke — APPROVED** [review]

**Pull request merged**
