### PR TITLE
changes routing to admin index page

### PR DESCRIPTION
**Pull request by nateptay**
This modifies the solution to use the name Admin across the startup routing, controllers, and views.

### CODE REVIEW

**Review by madelynmlocke — DISMISSED** [review]
Good naming conventions

**Review by MatinMirzaei — DISMISSED** [review]

**Review by SkutchWill — DISMISSED** [review]
Good fix

**Review by edmundchan8 — DISMISSED** [review]
Looks great to me!

**Comment by Bansenauer-Cascadia** [comment]
Nathan - this merge conflict shown suggest that you need to add a .gitignore file to the root folder of the repo. The gitignore file helps Git know which files to track and which ones to ignore, like the auto-generated files in the Debug folder. I recommend the one from GitHub at
https://raw.githubusercontent.com/github/gitignore/master/VisualStudio.gitignore

**Comment by Bansenauer-Cascadia** [comment]
Once you create the .gitignore file (yes, the filename does start with a period) with the contents from that link, you will need to use `git add .gitignore` to start tracking that file. It will keep any new files from being tracked, but it won't remove the tracking from existing files. To do that use this process... https://intellipaat.com/community/2837/git-stop-tracking-file-how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

**Comment by Bansenauer-Cascadia** [comment]
Nathan, I basically re-did what you tried, but in a slightly different order. It seems to have worked. Sorry you didn't get to push the BIG GREEN BUTTON to merge - it is quite a thrill ;-) 

You can (and should) still push the "Delete branch" button below to remove the branch and create a new branch from develop to continue working on your issue.

**Pull request merged**
