### PR TITLE
Uploaded Image appears on the Confirm View

### LINKED ISSUE #41: Having the logo icon appear as an icon/image on the confirmation screen
DoD: When the application user goes to the Confirmation screen, the section for the logo will show the actual logo they updated

Desc: Studying up how to code the application to and mostly the view to display an image of the logo, considering also the size of it and how it appears

User Story: When the application confirms it has accepted a logo for a business, on the application confirmation screen, there is actually no viewable logo.  Need to make it so that the updated logo appears.

### PR DESCRIPTION
**Pull request by edmundchan8**
When the form is completely filled in, the application will display the image that you uploaded as a Business Logo at 300x300 px on the confirm view.

### CODE REVIEW

**Review by madelynmlocke — DISMISSED** [review]

**Review by nateptay — DISMISSED** [review]
This works! I was able to merge it with my code validation to ensure the image gets loaded on the confirmation page.

**Review by SkutchWill — DISMISSED** [review]
Looks great

**Review by MatinMirzaei — DISMISSED** [review]

**Review by nateptay — DISMISSED** [review]

**Review by MatinMirzaei — DISMISSED** [review]

**Review by SkutchWill — DISMISSED** [review]
Works great

**Review by madelynmlocke — DISMISSED** [review]

**Review by nateptay — APPROVED** [review]

**Review by SkutchWill — APPROVED** [review]
re-reviewing after resolving conflicts

**Review by nateptay — APPROVED** [review]

**Review by madelynmlocke — APPROVED** [review]

**Review by MatinMirzaei — APPROVED** [review]

**Pull request merged**
