### PR TITLE
nateptay-ConfirmFeature

### PR DESCRIPTION
**Pull request by nateptay**
Modifies the confirmation page to include each piece of data from the form

### CODE REVIEW

**Review by madelynmlocke — APPROVED** [review]
Form looks good! Nice job in changing naming conventions to match models/viewmodels.

**Review by edmundchan8 — APPROVED** [review]
looks good

**Review by MatinMirzaei — APPROVED** [review]
Looking good

**Review by SkutchWill — APPROVED** [review]
Works perfectly, well done

**Pull request merged**
