### PR TITLE
Updated and switched to the corrected develop branch

### PR DESCRIPTION
**Pull request by MatinMirzaei**

### CODE REVIEW

**Review by edmundchan8 — COMMENTED** [review]
@MatinMirzaei Hey Matin,

Not sure why it doesn't show on github, but when I downloaded the code, I noticed you put in the HTML tags outside of the @layout.

There isn't a need for the HTML tags as the _Layout file already has it, and @layout will always pull those HTML tags into your view.

Other than that, everything loads and looks good!

**Review by edmundchan8 — APPROVED** [review]
I approve!

**Review by nateptay — APPROVED** [review]
Looks good!

**Review by SkutchWill — APPROVED** [review]
There are some built in data annotation validators that could be useful for the View Model.  Here is a link https://www.completecsharptutorial.com/asp-net-mvc5/data-annotation-validation-with-example-in-asp-net-mvc.php
specifically the phone number and url validation would be nice to have.

**Review by madelynmlocke — APPROVED** [review]

**Pull request merged**
