### PR TITLE
Api

### LINKED ISSUE #50: Create API controller for information retrieval
Create an API controller that will retrieve appropriate business information from the database to return to the mobile application.

### PR DESCRIPTION
**Pull request by SkutchWill**
I got the api working.  It can return json strings for queries based on category and names passed in a url request.  Tested and it works with businesses entered in the database

### CODE REVIEW

**Review by madelynmlocke — APPROVED** [review]
Great job with the API

**Review by edmundchan8 — APPROVED** [review]
looks good!

**Review by MatinMirzaei — APPROVED** [review]
looks good

**Review by nateptay — APPROVED** [review]
Awesome!

**Pull request merged**
