### PR TITLE
Added an API controller with a get request to return a business based…

### LINKED ISSUE #3: API Integration with Android App

### LINKED ISSUE #50: Create API controller for information retrieval
Create an API controller that will retrieve appropriate business information from the database to return to the mobile application.

### PR DESCRIPTION
**Pull request by SkutchWill**
So does anyone know if the database will be managed via the API or is the API just going to be used to package data to send to the app via Json

### CODE REVIEW

**Review by edmundchan8 — DISMISSED** [review]
Looks good to me

**Review by MatinMirzaei — DISMISSED** [review]

**Review by madelynmlocke — DISMISSED** [review]

**Review by nateptay — DISMISSED** [review]
Looks good!

**Review by MatinMirzaei — APPROVED** [review]

**Review by MatinMirzaei — APPROVED** [review]

**Comment by nateptay** [comment]
I think there's conflicts with the latest develop branch

**Comment by madelynmlocke** [comment]
Conflicts need to be resolved

**Pull request closed without merging**
