### PR TITLE
Added UnitTesting to application

### LINKED ISSUE #32: Learning how TDD is used in Web Applications with the goal to be confident enough to apply TDD to the OrcaStars Web Application in a future issue
DoD: When the assignee of this issue is confident with how TDD works in a web application

Desc: Studying up on TDD for future use in the OrcaStars Web Application

User Story: Currently, the team isn't fully confident on implementing TDD into the OrcaStars Web Application.  By reading up on it more, we hope to be able to gain confidence to create some Tests in the next/future sprint/s.

### PR DESCRIPTION
**Pull request by edmundchan8**
Unit test has been added to the project.  It Includes the Repositories folders, Services folders, Test Project folders and 2 tests to run that check the name and description of two businesses.

### CODE REVIEW

**Review by madelynmlocke — APPROVED** [review]
Looks good!

**Review by nateptay — APPROVED** [review]
Looks like a good start!

**Review by MatinMirzaei — APPROVED** [review]
Looking good

**Review by SkutchWill — APPROVED** [review]
I checked it out and I'm impressed with the tests you came up with.  They will be very useful when we get the database set up!

**Pull request merged**
