### PR TITLE
Updated previous branch with recent pull request code

### LINKED ISSUE #112: Adding placeholder text into the search fields of the search view
**DOD**: In the search view, the search input boxes have placeholder text to show what needs to be added

**Description**: Example text appears in the search input boxes of the search view

**User Story**: When the user goes to the search view, the search input boxes will show what can be added in

### PR DESCRIPTION
**Pull request by edmundchan8**
Closes #112

### CODE REVIEW

**Review by nateptay — CHANGES_REQUESTED** [review]
the e.g in Name and e.g. in city don't match with the number of .'s. I think we should use Orca Conservancy as the example business because the form is for the Orca Conservancy.

**Review by madelynmlocke — DISMISSED** [review]

**Comment by edmundchan8** [comment]
@nateptay @madelynmleahu Thanks, I updated the placeholder text if you guys want to check it out

**Review by madelynmlocke — APPROVED** [review]
Looks good

**Review by nateptay — APPROVED** [review]
Cool! looks good!

**Pull request merged**
