### PR TITLE
#66 Added Business List view to show a list of OrcaStars Businesses

### LINKED ISSUE #66: Create View for the Business List Page
This view also has options to edit and remove existing OrcaStar approved Businesses in the web application

### PR DESCRIPTION
**Pull request by edmundchan8**
Closes #66

### CODE REVIEW

**Review by MatinMirzaei — DISMISSED** [review]
looks good.

**Review by SkutchWill — DISMISSED** [review]
really nice work Edmund

**Review by nateptay — DISMISSED** [review]
Looks good! Is it intentional that the starting page is now the Business List page? Just curious

**Review by nateptay — APPROVED** [review]
looks good still!

**Review by MatinMirzaei — APPROVED** [review]

**Review by madelynmlocke — APPROVED** [review]

**Review by SkutchWill — APPROVED** [review]

**Comment by madelynmlocke** [comment]
Conflicts

**Comment by edmundchan8** [comment]
Closing - Madelyn made a search results view that does what this issue was to do

**Pull request closed without merging**
