### PR TITLE
Updates Logo DataType & Adds Updated NuGet Package

### LINKED ISSUE #26: Updating Database DataTypes
DoD: When user can store images/logos to database.

### PR DESCRIPTION
**Pull request by madelynmlocke**
Updates Logo data type to Bitmap, and adds updated System.Drawing NuGet Package in order for Bitmap to work.

### CODE REVIEW

**Review by edmundchan8 — DISMISSED** [review]
Looks good to me!

**Review by MatinMirzaei — DISMISSED** [review]
Looking good

**Review by nateptay — DISMISSED** [review]
I think this should work for the logo files

**Review by SkutchWill — DISMISSED** [review]
Excellent work, thank you!

**Review by nateptay — APPROVED** [review]
Cool.

**Review by edmundchan8 — APPROVED** [review]
I approve!

**Review by MatinMirzaei — APPROVED** [review]
looks good I approve

**Review by SkutchWill — APPROVED** [review]

**Pull request merged**
