### PR TITLE
Updated Business info part of   Business application

### PR DESCRIPTION
**Pull request by MatinMirzaei**

### CODE REVIEW

**Review by edmundchan8 — DISMISSED** [review]
Looks good

**Review by SkutchWill — DISMISSED** [review]
Looks good

**Review by nateptay — CHANGES_REQUESTED** [review]
It looks like the asp-validation-for tag on each of the inputs in Index.cshtml got removed. Can you make sure those are there?

**Review by edmundchan8 — DISMISSED** [review]
Approve!

**Comment by MatinMirzaei** [comment]
We decide to take another path

**Review by edmundchan8 — DISMISSED** [review]

**Review by SkutchWill — APPROVED** [review]
Looks great to me now

**Review by nateptay — DISMISSED** [review]
Looks good!

**Review by SkutchWill — DISMISSED** [review]

**Review by madelynmlocke — DISMISSED** [review]
Conflicts need to be resolved

**Review by nateptay — APPROVED** [review]

**Review by madelynmlocke — APPROVED** [review]
Conflicts resolved

**Review by edmundchan8 — APPROVED** [review]
Approved!

**Review by SkutchWill — APPROVED** [review]

**Pull request merged**
