### PR TITLE
Adds DbContext, Entity Models & DbContext Service

### LINKED ISSUE #5: Create entity model and database for application web form
Creating the database to store business information from the web form

### PR DESCRIPTION
**Pull request by madelynmlocke**
Adds Entity Models (Business, BusinessOwner), Edit class file BitDataContext, Installs EntityFrameworkCore NuGet Packages for DB, adds DBContext as service in Startup file

### CODE REVIEW

**Comment by madelynmlocke** [comment]
The Business Entity Model may need some work. Please review and give feedback for appropriate property data types for the following: 

- Hours (string)
- Logo (int)

**Review by MatinMirzaei — APPROVED** [review]

**Review by nateptay — COMMENTED** [review]
The business owner model looks good! It looks like Matin's Business Application View Model uses the following names/types for the businesses:
        public string BusinessName { get; set; }
        public string Description { get; set; }
        public string Website { get; set; }
        public string Coordinates { get; set; }
        public string SocialMedia { get; set; }
        public string Hours { get; set; }
        public string Logo { get; set; }

**Review by SkutchWill — DISMISSED** [review]
Data types look good to me.  As for the logo we can do that in another sprint.  Usually you store a reference to the image and not the image file itself in the database.  I think string is correct for hours if we are storing the hours together.  If we wanted to make it cleaner we could create an opening and closing hour property that are stored as the date-time type.  Then we get into the issue of different days having different hours of operation plus holidays so it depends on how far we want to go for that detail.

**Review by MatinMirzaei — DISMISSED** [review]

**Review by edmundchan8 — DISMISSED** [review]
I Approve!

**Comment by MatinMirzaei** [comment]
Looking good

**Review by nateptay — DISMISSED** [review]

**Comment by Bansenauer-Cascadia** [comment]
I suggest you research a bit more about C# data types for the properties Hour, Coordinates and Logo. 

https://www.google.com/search?q=c%23%20data%20types%20for%20coordinates&ie=utf-8&oe=utf-8&client=firefox-b-1-m

**Review by MatinMirzaei — DISMISSED** [review]

**Comment by madelynmlocke** [comment]
image data type property will roll to next sprint. coordinates data type completed

**Review by edmundchan8 — DISMISSED** [review]
Approve!

**Review by SkutchWill — DISMISSED** [review]
For next sprint we need Logo to be Bitmap datatype, Coordinates to be split up into latitude and longitude (both double type), and hours to be split up to opening and closing and stored as time data type.

**Review by nateptay — APPROVED** [review]
Seems to work, let's merge this soon!

**Review by edmundchan8 — APPROVED** [review]
Checked out and looks great!

**Review by SkutchWill — APPROVED** [review]
Works great!

**Review by MatinMirzaei — APPROVED** [review]

**Pull request merged**
